baseurl = "http://eriqnelson.com"
title = "Eriq Nelson"
theme = "dimension"
languageCode = "en-us"
defaultContentLanguage = "en"
enableRobotsTXT = true
disableRSS = true

[params]
  title = "Eriq Nelson"
  description = '<!--[-->Opinions about Work and <!--]--><br />
                <!--[-->Software<!--]-->'
  logo = "fa-code"
  copyright = "Eriq Nelson CC BY 4.0"

[[params.social]]
  medium = "twitter"
  icon = "twitter"
  link = "https://twitter.com/EriqNelson"


[[params.social]]
  medium = "github"
  icon = "github"
  link = "https://github.com/eriqnelson"

  [[params.social]]
    medium = "keybase"
    icon = "key"
    link = "https://keybase.io/eriqnelson"


[languages]
[languages.en]
languageName = "English"
weight = 1
title = "Eriq Nelson"
